- name: Rootless Containers
  hosts: localhost
  tasks:
    - name: sshd service
      become: true
      systemd:
        name: sshd
        state: started
        enabled: yes

    - name: Login
      ansible.builtin.assert:
        that:
          - lookup('ansible.builtin.env', 'XDG_RUNTIME_DIR') == '/run/user/1000'
    
    - name: Get current user's UID
      command: id -u {{ ansible_user_id }}
      register: uid
      changed_when: false
      no_log: true

    - name: Get current arch
      command: uname -m
      register: uname
      changed_when: false

    - name: Generate /etc/subuid lines for current user
      become: true
      lineinfile:
        path: /etc/subuid
        line: "{{ lookup('env','USER') }}:{{ uid.stdout }}00000:65536"
        create: yes
    - name: Generate /etc/subgid lines for current user
      become: true
      lineinfile:
        path: /etc/subgid
        line: "{{ lookup('env','USER') }}:{{ uid.stdout }}00000:65536"
        create: yes

    # - name: kernel mods
    #   become: true
    #   lineinfile:
    #     path: /etc/sysctl.d/rootless-docker.conf
    #     line: kernel.unprivileged_userns_clone=1
    #     create: yes
    
    - name: Check for docker
      stat:
        path: ~/bin/dockerd
      register: docker_exists

    - name: Download Docker rootless installer
      ansible.builtin.get_url:
        url: http://get.docker.com/rootless
        dest: /tmp/rootless-docker.sh
      when: not docker_exists.stat.exists
      notify: Install rootless docker

    - name: Check for slirp4netns
      stat:
        path: ~/bin/slirp4netns
      register: slirp4netns_exists
    - name: Download slirp4netns
      ansible.builtin.get_url:
        url: https://github.com/rootless-containers/slirp4netns/releases/download/v1.2.0/slirp4netns-{{ uname.stdout | string }}
        dest: ~/bin/slirp4netns
        mode: 0777
      when: (not slirp4netns_exists.stat.exists)
      notify: Set slirp4netns as port forwarder
      

# set export DOCKER_HOST=unix:///run/user/$(id -u $USER)/docker.sock
# set export PATH=$HOME/bin:$PATH

  handlers:
    - name: Set slirp4netns as port forwarder
      copy:
        content: |
                  [Service]
                  Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns"
        dest: ~/.config/systemd/user/docker.service.d/override.conf
        
    - name: Install rootless docker
      ansible.builtin.script: /tmp/rootless-docker.sh
      args:
        executable: sh
