tunnel: <tunnel name or ID>
credentials-file: /etc/cloudflared/<tunnel ID>.json
ingress:
  - hostname: <subdomain>.descention.net
    service: https://<docker host IP>:<other service port>
  - service: https://<docker host IP>:443
    originRequest:
      noTLSVerify: true