version: "2.4"

services:
  cloudflare:
    image: cloudflare/cloudflared:2021.11.0
    container_name: cloudflared
    restart: unless-stopped
    volumes:
      - ${BASE_DIR}/cloudflared:/etc/cloudflared
    command: tunnel --config /etc/cloudflared/config/config.yaml run
    depends_on:
      - traefik
    networks:
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # TODO: https://kevinquillen.com/setting-traefik-2-local-ssl-certificate
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.defaultrule=Host(`{{ index .Labels \"com.docker.compose.service\" }}.descention.net`)"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certResolver=letsencrypt"
      - "--certificatesresolvers.letsencrypt.acme.email=scott.mundorff@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/srv/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--log.level=info"
      - "--entrypoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1/32,173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${BASE_DIR}/traefik/ssl:/srv
    networks:
      - web
  
  archivebox:
    extends:
      file: services/archivebox.yml
      service: archivebox

  homebridge:
    extends:
      file: services/homebridge.yml
      service: homebridge
  
  vault:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - DOMAIN=https://vault.descention.net
      - SIGNUPS_ALLOWED=false
      - SIGNUPS_VERIFY=true
      - SMTP_HOST=${VAULT_SMTP_HOST}
      - SMTP_PORT=465
      - SMTP_SSL=false
      - SMTP_EXPLICIT_TLS=true
      - SMTP_FROM=${VAULT_SMTP_FROM}
      - SMTP_USERNAME=${VAULT_SMTP_USERNAME}
      - SMTP_PASSWORD=${VAULT_SMTP_PASSWORD}
      - SMTP_AUTH_MECHANISM=${VAULT_SMTP_AUTH_MECHANISM}
      #- ADMIN_TOKEN=${VAULT_ADMIN_TOKEN}
    volumes:
      - ${BASE_DIR}/vaultwarden-server:/data
    networks:
      - web
    labels:
      - "traefik.enable=true"

  photos:
    extends:
      file: services/photoprism.yml
      service: photos

  mariadb:
    extends:
      file: services/photoprism.yml
      service: mariadb

  resilio:
    extends:
      file: services/resilio.yml
      service: resilio-sync
      
  # watchtower to keep containers updated
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_POLL_INTERVAL=7200 # checks for updates every two hours
networks:
  web: {}
  internal: {}
