version: '3.0'
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs
    command: daemon
    restart: unless-stopped
    volumes:
      - ${BASE_DIR}/ipfs/data:/data/ipfs
      - ${BASE_DIR}/ipfs/staging:/export
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
      - 5001:5001
      - 8999:8080
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ipfs.loadbalancer.server.port=8999" # set port assignment