version: '2.4'
services:
  monica:
    image: monica
    depends_on:
      - monicadb
    ports:
      - 80
    environment:
      APP_ENV: "production"
      APP_KEY: "${MONICA_APP_KEY}"
      DB_HOST: "monicadb:3306"
      DB_USERNAME: "usermonica"
      DB_PASSWORD: "${MONICA_MYSQL_PASSWORD}"
    volumes:
      - ${BASE_DIR}/monica/data:/var/www/html/storage
    restart: unless-stopped
    networks:
      - web
      - internal
    labels:
      - "traefik.enable=true"
  monicadb:
    image: mariadb:10.8
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_ROOT_PASSWORD: "${MARIA_DB_PASS}"
      MARIADB_DATABASE: "monica"
      MARIADB_USER: "usermonica"
      MARIADB_PASSWORD: "${MONICA_MYSQL_PASSWORD}"
    command: mysqld --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120 --innodb_default_row_format=dynamic --innodb_file_format=Barracuda --innodb_large_prefix=1
    volumes:
      - ${BASE_DIR}/monica/db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - internal
      