version: "2.4"
services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${BASE_DIR}/resilio/config:/config
      - ${BASE_DIR}/resilio/downloads:/downloads
      - ${BASE_DIR}/resilio/sync:/sync
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped