version: '2.4'
services:
  yacy:
    image: yacy/yacy_search_server:latest
    container_name: yacy
    ports:
      - 8090:8090
    volumes:
      - ${BASE_DIR}/yacy:/opt/yacy_search_server/DATA
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.yacy.loadbalancer.server.port=8090" # set port assignment
    logging:
      options:
        max-size: "100m"
        max-file: "2"